export { AuthProvider } from './AuthProvider'
export { useAuth, useSession, useRole, usePerfil } from './hooks'
export { atualizarPerfil, buscarPerfil, perfilIncompleto, statusTelefone, verificarSessao } from './perfil'
export { homeDoPapel } from './papeis'
export { nextSeguro } from './redirect'
export { useTemVinculoDevedor } from './useVinculoDevedor'
export { mensagemDeErroAuth } from './erros'
export { OtpTelefoneDialog } from './OtpTelefoneDialog'
export type { AuthState, AuthStatus } from './context'
